name: Deploy Aws
on: push

jobs:
  deploy_aws:
    runs-on: ubuntu-latest

    steps:
      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.REMOTE_IP }} # 인스턴스 IP
          username: ${{ secrets.REMOTE_USER }} # 우분투 아이디
          key: ${{ secrets.REMOTE_PRIVATE_KEY }} # ec2 instance pem key
          port: ${{ secrets.REMOTE_SSH_PORT }} # 접속포트
          script: | # 실행할 스크립트
            cd /home/ubuntu/Salt-bot
            git pull origin main
            pm2 kill
            npm i --force
            npm run build
            pm2 start dist/main.js

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Setup firebase admin json
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "msg-salty-firebase-adminsdk.json"
          json: ${{ secrets.FIREBASE_JSON }}

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libffi-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt