name: Deploy Aws
on:
  push:
    branches:
      - master

jobs:
  deploy_aws:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: ls

      - name: excuting remote ssh commands
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd /home/ubuntu/salt-bot
            pm2 kill
            npm i --force
            npm run build
            pm2 start dist/index.js